【WIP】 Objectクラスの作成
human-osaka-game-2018/NinjaResidence pull request #2
Opened 2018-11-17 12:58 UTC by ToshiyaMatsuoka

# 変更予定内容
* [x] MapChipクラスとGameCharaクラスを集約したクラスを作成する
* [ ] 構造的にまずいGameCharaクラスがMapChipクラスのインスタンスを保持している点の修正
* [ ] 上記内容によって変更を必要とする箇所の変更

2018-11-17 14:38 UTC, taishi-matsumura commented
このPRでやることリストのチェックボックスとか素敵❤️

2018-11-20 02:33 UTC, Harutaka-Tsujino requested changes

2018-11-20 02:33 UTC, Harutaka-Tsujino commented on NinjaResidence/DirectXlib.cpp
> +	DrowSceneBegin();
DrawがDrowになっていますよ

2018-11-20 02:33 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMESCENE.cpp
> +			m_pMapChip->setMapScrollY (m_pGameChara->KeyOperation(UP));
この処理はUPキーが押されたらどのような処理を起こすのかわかりにくい気がします
m_pGameChara->KeyOperation(JUMP)のほうが分かりやすい気がします

2018-11-20 02:37 UTC, ToshiyaMatsuoka commented on NinjaResidence/DirectXlib.cpp
> +	DrowSceneBegin();
修正します

2018-11-20 02:46 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMESCENE.cpp
> +			m_pMapChip->setMapScrollY (m_pGameChara->KeyOperation(UP));
ここのEnumの値は作業途中で仮に四方向を示すだけにしています。
指摘の通りにした方がわかりやすいと思うので変えます。

2018-11-20 02:48 UTC, Harutaka-Tsujino requested changes

2018-11-20 02:48 UTC, Harutaka-Tsujino commented on NinjaResidence/DirectXlib.cpp
> +		for (int i = 0; i < 0xED; i++) {
0xEDが何か意図があるかのように感じてしまいます
KEY_MAXのような定数を用意したほうがいいのではないでしょうか

2018-11-20 02:49 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMEMANAGER.cpp
> +	Wndclass.lpszClassName = TEXT("�E�҉��~");	//�N���X��
TEXTの省略形で_Tがありますよ

2018-11-20 02:56 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMESCENE.h
> +	DirectX* m_pDirectX;
クラスのポインタなどで初めにm_pDirectX = nullptr;のようにしておくとデバッグするときに
ゴミが入らないのでデバイスが生成されていなかった時わかりやすくていいですよ

2018-11-20 02:56 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.cpp
> +	Wndclass.lpszClassName = TEXT("�E�҉��~");	//�N���X��
tcharのヘッダーを入れていない為TEXT()のマクロになっています。

2018-11-20 03:04 UTC, ToshiyaMatsuoka commented on NinjaResidence/DirectXlib.cpp
> +		for (int i = 0; i < 0xED; i++) {
意図としてはループ回数を減らすために
DIKの最大値である237を入れています。
理解しやすいので今後そのように変えると思います。

2018-11-20 03:13 UTC, shion-sagawa commented
すみませんが今はLonelyで作業に追われていて、レビューする余裕がないです。
終わり次第レビューしますが、期待しないでください。

2018-11-20 04:35 UTC, Harutaka-Tsujino approved these changes

2018-11-21 04:00 UTC, merged