SoundLib実装
human-osaka-game-2018/NinjaResidence pull request #3
Opened 2018-11-21 04:23 UTC by ToshiyaMatsuoka

変更予定
--
* [x] SoundLib使用準備
* [x] 音声が再生されていることを確認する

2018-11-26 00:32 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMEMANAGER.h
>  	static bool WinMode;	//true:Window�@false:Full
変数名だけでフラグということが分かりにくいです

2018-11-26 00:48 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
>  	static bool WinMode;	//true:Window�@false:Full
trueであるとどうなるのかわかりにくいということでしょうか。
少し考えて名称変更します。

2018-11-28 01:27 UTC, taishi-matsumura requested changes
とりあえず。

2018-11-28 01:27 UTC, taishi-matsumura commented on NinjaResidence/GAMEMANAGER.h
> +#pragma comment(lib,"SoundLib.lib")
リンクするライブラリの指定はcppに書くべきな気がします。
ヘッダファイルの中は、(関数含め)型の話に留めておかないとぐちゃぐちゃになりそうです。

2018-11-28 01:27 UTC, taishi-matsumura commented on NinjaResidence/GAMEMANAGER.h
> +	static SoundLib::SoundsManager* pSoundManager;
上で `using SoundLib::SoundsManager` と書くのなら
```suggestion
	static SoundsManager* pSoundManager;
```
で良いのでは？

2018-11-28 01:27 UTC, taishi-matsumura commented on NinjaResidence/GameChara.h
>  };
ファイル末尾に改行入れておきましょう。

2018-11-28 01:27 UTC, taishi-matsumura commented on NinjaResidence/SceneManager.h
> +	SoundsManager* m_pSoundManager = NULL;
constポインタじゃダメですか？
もしこれはダメだったとしても、ポインタ変数が出てきたらconstにできないかを常に考えるようにして下さい。

2018-11-29 02:47 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
> +#pragma comment(lib,"SoundLib.lib")
ヘッダの中身は改めて情報の取捨選択していきます

2018-11-29 02:49 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
> +	static SoundLib::SoundsManager* pSoundManager;
using宣言は後で加えたので
指摘箇所の”SoundLib::”は消し忘れていました。

2018-11-29 02:53 UTC, ToshiyaMatsuoka commented on NinjaResidence/SceneManager.h
> +	SoundsManager* m_pSoundManager = NULL;
constポインタの使えるところ考えていきます

2018-12-03 09:56 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
>  };
直しました！

2018-12-03 12:36 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
> +	static SoundLib::SoundsManager* pSoundManager;
指摘箇所消去しました。

2018-12-03 14:26 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
> +#pragma comment(lib,"SoundLib.lib")
リンクするライブラリの指定をcpp内に移動しました。

2018-12-03 14:26 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMEMANAGER.h
> +	static SoundLib::SoundsManager* pSoundManager;
消去しました。

2018-12-03 14:47 UTC, taishi-matsumura approved these changes

2018-12-04 00:35 UTC, merged