Wipkawahara
human-osaka-game-2018/NinjaResidence pull request #4
Opened 2018-11-21 05:10 UTC by koujiroukawahara

2018-11-21 05:13 UTC, koujiroukawahara commented
Yの当たり判定の制作  Xの当たり判定の変更 Yのスクロール追加

2018-11-22 14:15 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +	m_prevMapCharaPositionX = (int)m_WorldCharaCoordinate[3].x;
C言語のキャストはよろしくないのでC++のキャストを使うほうが良いです。

2018-11-22 14:15 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +		m_WorldCharaCoordinate[0].y -= 30.f;
大量にあるマジックナンバーですが、定数にしないのはなぜですか？。
加えて、配列の各要素に同一の値を入れているのならばループで回してしまえば良いと思いますが、
どのような意図でしょうか？

2018-11-22 14:15 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +void GameChara::Update()
関数の大きさが80行近くあるのは一関数の内容として濃すぎると思うので、
もう少し関数を分けたほうが良いと思います。

2018-11-22 14:15 UTC, ToshiyaMatsuoka commented on NinjaResidence/Object.h
> +	int m_MapScrollX = 0;
ここの記述がどうこうではないですがクラスの構造として、publicにメンバ変数を書かなければいけない構造はおかしくありませんか？

2018-11-22 17:46 UTC, Harutaka-Tsujino requested changes

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMESCENE.cpp
>  	return Getm_NextScene();
Getterが返すのがメンバの値ということはわかりきっているので
```suggestion
	return GetNextScene();
```
でいいような気がします

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/GameChara.cpp
> +		m_WorldCharaCoordinate[0].y -= 30.f;
キャラクターの移動などは関数などにしてしまったほうがいいと思います

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/GameChara.cpp
> +	if (m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX + 1) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,M
if分の中の条件式が長すぎるような気がします
```suggestion
	if (m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX)    ||
	 　m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX + 1) ||
	 　m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX + 2) )
```
これではだめなのですか？
負の値がVisualStudio2017ではfalseとしてとられるのでそれを意識してなら申し訳ないです
折り曲げるだけでも見やすくなるのでやってみてください

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/GameChara.cpp
> +	if (m_prevMapCharaPositionX >= m_WorldCharaCoordinate[3].x)
m_の後は大文字なのか小文字なのか統一してください

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/MapChip.h
>  };
ファイルの終わりは改行を行ってください

2018-11-22 17:46 UTC, Harutaka-Tsujino commented on NinjaResidence/DirectX.cpp
>  #define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_TEX1)
この定数がマクロである必要はないと思うのでconstにしてはどうですか

2018-11-22 18:04 UTC, taishi-matsumura commented on NinjaResidence/Object.h
> +	int m_MapScrollX = 0;
publicなメンバ変数はルール違反ですね〜

2018-11-22 18:07 UTC, taishi-matsumura commented on NinjaResidence/GameChara.cpp
> +	if (m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX + 1) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,M
「折り曲げる」よりも「改行する」と言いましょうｗ

2018-11-26 01:37 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +	m_prevMapCharaPositionX = (int)m_WorldCharaCoordinate[3].x;
やり方を調べて直します

2018-11-26 01:39 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +		m_WorldCharaCoordinate[0].y -= 30.f;
キャラの移動速度のdefineにする予定だったのですが、単純にdefineにし忘れてました

2018-11-28 05:27 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +void GameChara::Update()
関数にしました

2018-11-28 05:29 UTC, koujiroukawahara commented on NinjaResidence/Object.h
> +	int m_MapScrollX = 0;
他の.cppと.ｈ内で使うのはGeterとSetetにして全部privateにしました

2018-11-28 05:31 UTC, koujiroukawahara commented on NinjaResidence/GAMESCENE.cpp
>  	return Getm_NextScene();
なおしました

2018-11-28 05:32 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +		m_WorldCharaCoordinate[0].y -= 30.f;
関数かしました

2018-11-28 05:33 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +	if (m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,MapCharaPositionX + 1) != 0 || m_pMapChip->getMapChipData(MapCharaPositionY,M
改行しました

2018-11-28 05:33 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +	if (m_prevMapCharaPositionX >= m_WorldCharaCoordinate[3].x)
統一しました

2018-11-28 05:35 UTC, koujiroukawahara commented on NinjaResidence/MapChip.h
>  };
改行いれました

2018-11-28 05:37 UTC, koujiroukawahara commented on NinjaResidence/DirectX.cpp
>  #define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_TEX1)
担当松岡です

2018-11-28 05:52 UTC, Harutaka-Tsujino commented on NinjaResidence/DirectX.cpp
>  #define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZRHW | D3DFVF_DIFFUSE | D3DFVF_TEX1)
いったん閉じておきます

2018-11-28 05:52 UTC, Harutaka-Tsujino approved these changes

2018-11-28 06:32 UTC, Harutaka-Tsujino requested changes
まだ定数で置ききれてないので定数でおいてください

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/MapReverse.h
> +	MapReverse1 MapReverse1;
ここの型はBOOL型ではいけない理由は何でしょうか？
表か裏かの2択しか無いはずですよね？

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/MapReverse.cpp
> +		m_pMapChip->Create("csv/Book2.csv");
ここで
* CharaInforSaveメソッドの引き数を直接生の値を渡している理由
* わざわざ表と裏を分けて情報の保存をする意味
* マップのCreateメソッドをどんでん返し実行のたびに行う意味
以上の点がわからないです

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/MapReverse.cpp
> +	if (m_pMapChip->getMapChipData((m_pGameChara->GetMapCharaPositionY() - 1),( m_pGameChara->GetMapCharaPositionX() - 1))  != 3 &&
同一の値を呼ぶのに毎回関数を呼ぶのは処理がだるいので
```
int MapPosX= m_pGameChara->GetMapCharaPositionX();
int MapPosY=m_pGameChara->GetMapCharaPositionY();
if (m_pMapChip->getMapChipData((MapPosY- 1),(MapPosX - 1))  != 3 &&......
```
このようにしたほうが良いと思います。

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
名前のほぼ全てにCharaと入れているのはなぜですか？
ゲームキャラクラスのメンバであるのだからゲームキャラに関するなにかであることは明白ですよね？

後、MapCharaPositionXとMapCharaPositionX2は何がどう異なる値であるのか理解し難いです。

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
> +class MapReverse;
必要ないならこの前方宣言は消しましょう。

2018-11-29 05:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +	if (m_DisplayCharaCoordinate[1].y < 200)
ここの中のマジックナンバーはキャラの位置が決まれば全て計算で算出させることが出来るので計算で出すようにしたほうが良いでしょう。

2018-11-29 05:10 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +void GameChara::Update()
どこが関数になり、分けられたのかわかりません。
関数一個の行数を40行程度に縮めるようにできませんか？

2018-11-29 14:28 UTC, koujiroukawahara commented on NinjaResidence/GameChara.cpp
> +void GameChara::Update()
GameCharaのUpdateの中身をもっと短くってことやったら毎フレーム重力かけるところとかも関数化したほうがいい？

2018-11-29 14:35 UTC, koujiroukawahara commented on NinjaResidence/MapReverse.h
> +	MapReverse1 MapReverse1;
2択やからbool型じゃなくて普通のenum型です。この場合、普通のenum型であってますか？

2018-11-29 16:40 UTC, koujiroukawahara commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
マップ上でのキャラの位置って意味でMapCharaPositionにしてます
違いはMapCharaはキャラの左下の値でMapChara2はキャラの右下の値で分けてます

2018-11-29 16:43 UTC, koujiroukawahara commented on NinjaResidence/GameChara.h
> +class MapReverse;
了解です

2018-11-29 17:06 UTC, koujiroukawahara commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
この値は配列番号なので計算する時にMapCharaに＋2しても大丈夫なんやけどそっちのほうがいいかな？

2018-11-29 23:20 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.cpp
> +void GameChara::Update()
コードが見やすくなるのならする方がいいです。
update関数においてはどれだけ数値の重力がかかっているのかなんてどうでもいい話のはずなので

2018-11-29 23:29 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
この場合、番号で分けるのではなく左右のどちらであるのかを変数名とするべきだと思います。

+2という値を定数として入れていくなら計算時に入れていくでもいいかもしれません。

2018-11-30 00:06 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
メンバの変数名、関数名にCharaと入れていることに関して
アクセス時にキャラー＞メンバ名となるので**キャラの何か**以外であるはずがない。
ということはキャラのマップ上の位置なら変数名として適当なのは
”誰のマップ上の位置“ではなくて”**マップ上の位置**“だけでいいのでは？

2018-12-01 02:41 UTC, koujiroukawahara commented on NinjaResidence/GameChara.h
> +	void CharaMoveOperation(KeyDirection vec, CUSTOMVERTEX* pWorldCharaCoordinate, CUSTOMVERTEX* pDisplayCharaCoordinate, float MoveQuantity);
変数の名前は
MapCharaPositionの方がMapLeftDirectionPosition(マップ上で左向きの位置)
MapCharaPosition2の方がMapRightDirectionPosition(マップ上で右向きの位置)
こんな感じ？

2018-12-01 02:44 UTC, koujiroukawahara commented on NinjaResidence/MapReverse.cpp
> +	if (m_pMapChip->getMapChipData((m_pGameChara->GetMapCharaPositionY() - 1),( m_pGameChara->GetMapCharaPositionX() - 1))  != 3 &&
確かにその方が良さそうなのでそうします

2018-12-01 02:56 UTC, koujiroukawahara commented on NinjaResidence/MapReverse.cpp
> +		m_pMapChip->Create("csv/Book2.csv");
1.こっちの見逃しかもしれんけどCharaInforSaveって関数が見つからない.
2.それ以外がわからないかった。処理的にもわかりやすくない？
3.毎回Createするのはすごい大げさな処理と確かに思う。松岡や辻野の言う通りステージ事に最初からマップ2個Createして判定や描画を入れ替えるだけにしたいんやけどやり方が思い浮かばない。ごめんなさい

2018-12-03 05:16 UTC, ToshiyaMatsuoka approved these changes
まだ未変更箇所はありますが急ぎの箇所は治っていると思うので承認入れておきます。

2018-12-03 05:34 UTC, Harutaka-Tsujino approved these changes

2018-12-03 07:12 UTC, merged