Wipkawahara
human-osaka-game-2018/NinjaResidence pull request #6
Opened 2018-12-04 05:53 UTC by koujiroukawahara

どんでん返しの処理を表の5番は裏の5番、表の６番は裏の６に繋がっているという処理にしました、

2018-12-04 05:59 UTC, Harutaka-Tsujino commented on NinjaResidence/GAMESCENE.h
> +	GameChara * m_pGameChara = NULL;
型と＊の間にスペースができているので整えてください

2018-12-11 01:35 UTC, taishi-matsumura commented
masterから枝分かれした状態にして、元のwipkawaharaブランチにコミットされていた内容から bcd75aa だけ取り込みました。
下記コミットは衝突が多くて僕の知識では取り込めなかったので、すみませんがチームメンバで対応して下さい。
- b30058f
- 28e7ec7
- 16ee8b1

元のkawaharaブランチの内容は [matsumuraブランチ](https://github.com/human-osaka-game-2018/NinjaResidence/commits/matsumura) に退避しています。

2018-12-11 03:45 UTC, ToshiyaMatsuoka commented on NinjaResidence/MapChip.cpp
> +				CELL[3].tv = BLOCK_HEIGHT;
必ず修正しろとは言いませんが、CELLに値を代入している8行を関数にしておくと今後のブロック追加時に楽になると思います。

2018-12-11 03:46 UTC, ToshiyaMatsuoka requested changes

2018-12-11 03:46 UTC, ToshiyaMatsuoka commented on NinjaResidence/DescriptionBoard.h
> +};
ファイル末尾の改行足しましょう

2018-12-18 02:30 UTC, koujiroukawahara commented on NinjaResidence/DescriptionBoard.h
> +};
足しました

2018-12-20 06:45 UTC, koujiroukawahara commented on NinjaResidence/DescriptionBoard.h
> +};
直しました

2018-12-21 13:10 UTC, ToshiyaMatsuoka requested changes
指摘は一つだけにしていますが、マージしたときのゴミが残っています。
早急に修正願います。

2018-12-21 13:10 UTC, ToshiyaMatsuoka commented on NinjaResidence/DescriptionBoard.h
> +	GameChara * m_pGameChara = NULL;
ここも前から指摘されている箇所です。
`GameChara* m_pGameChara = NULL;`
の形式に修正してください

2018-12-21 13:10 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMESCENE.cpp
> +<<<<<<< HEAD
ゴミが入ったままです。
コンパイル通らないので消去してください

2018-12-26 01:28 UTC, Harutaka-Tsujino approved these changes
確認しました

2018-12-26 01:29 UTC, ToshiyaMatsuoka approved these changes

2018-12-26 01:29 UTC, merged