【WIP】キャラクター動作
human-osaka-game-2018/NinjaResidence pull request #7
Opened 2018-12-06 00:57 UTC by ToshiyaMatsuoka

2018-12-11 10:10 UTC, taishi-matsumura requested changes

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/DirectX.h
> +	bool ChackPushAnykey();
スペルミスだし、そもそもboolを返す関数名に`CheckXXX`はやめよう

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/DirectX.cpp
> +	}
範囲for使えばこんな風に書けませんか？(動作は未確認です)
```
	for (auto keyState : m_KeyState) {
		if (keyState != 0) {
			return true;
		}
	}
```

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/DirectX.h
> +	const int MaxKeyNumber = 256;
```suggestion
	static const int MaxKeyNumber = 256;
```
ってして`m_KeyOldState`とかより上に書いておけば、
```
	BYTE m_KeyOldState[MaxKeyNumber];
	BYTE m_KeyState[MaxKeyNumber];
```
みたいにマジックナンバー消せますよ。

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/DirectX.h
> +	bool ChackPushAnykey();
publicメソッドなのでdoxygenコメント入れておきましょう。

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/GAMESCENE.cpp
> +void GameScene::CheckPushAnyButton() {
何かキーが押されていたら何もしない関数？
関数名見て中身見て混乱しました。結局何してるのかよくわかりません。

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/GAMESCENE.h
> +	void Reverce();
```suggestion
	void Reverse();
```

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/SCENE.cpp
>  	CENTRAL_STATE CLOSS = { CENTRAL_X,CENTRAL_Y,300,300 };
今回のレビュー対象では無いですが、
```suggestion
	CENTRAL_STATE CROSS = { CENTRAL_X,CENTRAL_Y,300,300 };
```
では？

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/Shuriken.cpp
> +		isActive = PermitThrow();
メンバ変数なのにプレフィクス`m_`無し？他と合わせていきましょう。
プレフィクス付けないとう方針でも良いと思いますが(付けるのはold styleなので付けない方が良いという意見もありますね)、lower camelだとローカル変数と見分けが付かないので`this->`を付けた方が良いと思います。

2018-12-11 10:10 UTC, taishi-matsumura commented on NinjaResidence/Shuriken.h
> +class Object;
Object.hをincludeしているのに前方宣言？

2018-12-12 02:40 UTC, ToshiyaMatsuoka commented on NinjaResidence/Shuriken.cpp
> +		isActive = PermitThrow();
メンバ変数にはプレフィックス```m_```つけるように統一するようにします。

2018-12-12 02:42 UTC, ToshiyaMatsuoka commented on NinjaResidence/GAMESCENE.cpp
> +void GameScene::CheckPushAnyButton() {
何もキーが入力されていないときに動作する関数ということで作成しました。
関数名の変更しました。

2018-12-12 02:43 UTC, ToshiyaMatsuoka commented on NinjaResidence/DirectX.cpp
> +	}
授業であったように```std::find_if()```で判断するように変更しました。

2018-12-12 02:44 UTC, ToshiyaMatsuoka commented on NinjaResidence/Shuriken.h
> +class Object;
includeが不要だったので消去しました

2018-12-12 02:45 UTC, ToshiyaMatsuoka commented
名称のスペルミスについては指摘のところに修正入れました。

2018-12-12 02:46 UTC, ToshiyaMatsuoka commented on NinjaResidence/DirectX.h
> +	const int MaxKeyNumber = 256;
指摘の通りに変更しました

2018-12-12 02:50 UTC, taishi-matsumura commented on NinjaResidence/Shuriken.h
> +class Object;
辻野のところとは違って、前方宣言を積極的に利用する方針なのですね。了解です。

2018-12-12 03:13 UTC, taishi-matsumura requested changes
もう一声って感じ

2018-12-12 03:13 UTC, taishi-matsumura commented on NinjaResidence/DirectX.cpp
> +	BYTE* tmp = std::find_if(std::begin(m_KeyState), std::end(m_KeyState), [](BYTE m_KeyState) {return m_KeyState; });
* ラムダ式の仮引数は `DirectX::m_KeyState` では無くその中の各要素のはずなので名前変えましょう
* ラムダ式の戻り値は、何をチェックして真偽を判断しているのかを明示した方がわかりやすいと思います
```suggestion
	BYTE* tmp = std::find_if(std::begin(m_KeyState), std::end(m_KeyState), [](BYTE keyState) { return keyState != 0; });
```
こんな感じの方が良いと思います。

2018-12-12 03:13 UTC, taishi-matsumura commented on NinjaResidence/DirectX.h
> +	bool PushAnykey();
これは無いわー。
けど「じゃあ何が良い？」と言われても困る系。
うーん、
```suggestion
	bool IsAnykeyPressed();
```
とかかなぁ。
https://qiita.com/ikngtty/items/3125c2210b8623a70311

2018-12-12 03:23 UTC, taishi-matsumura commented on NinjaResidence/GAMESCENE.cpp
> +void GameScene::CheckPushAnyButton() {
そもそもCharaとの役割分担がキモいのかなぁ。
違和感無くなるようにちょっとずつ修正していきましょうか。

2018-12-12 08:13 UTC, taishi-matsumura reviewed
「プログラミングやコンピュータから切り離してクラスやメソッドに命名する」という選択肢も持っておくと良いと思います。

2018-12-12 08:13 UTC, taishi-matsumura commented on NinjaResidence/GameChara.h
> +	void NoOperation();
現状のコードのように「キー操作された」「無操作だった」というようなメソッド名にする以外に、 `Move()` とか `Wait()` といった命名の仕方もあります。
後者の方がより「何かをモデリングした感」が出るので個人的にはそちらが好きなのですが、この辺は宗教みたいなものだと思います。
GameCharaをどう捉えるかという目線の問題ですね。

2018-12-12 08:14 UTC, taishi-matsumura approved these changes

2018-12-13 02:07 UTC, ToshiyaMatsuoka commented on NinjaResidence/GameChara.h
> +	void NoOperation();
今後、```NoOpetation```に今以上の内容が入っていくのでそのときにリネームを考えたいと思います。

2018-12-13 02:17 UTC, merged